# -*- coding: utf-8 -*-
"""arabic_dialect_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9HjT0rc3XRVRg2dViTdfsiqaqeIlo9A

# Arabic Dialect Classification

This project aims to classify Arabic text into dialect categories using both traditional machine learning and deep learning approaches.

The focus of this notebook is binary classification between:
- Khaleeji
- Masri

We compare:
- Logistic Regression with TF-IDF
- LSTM with tokenized sequences

## Problem Statement

Arabic has many dialects that differ across regions. These dialectal differences make automatic dialect identification a challenging Natural Language Processing task.

The goal of this project is to build models that can classify Arabic text into its corresponding dialect based on linguistic patterns in the text.

## Objectives

- Load and prepare an Arabic dialect dataset
- Filter the dataset for selected dialects
- Clean and preprocess Arabic text
- Train a machine learning model using TF-IDF
- Train a deep learning model using LSTM
- Compare the performance of both approaches

##libraries
"""

from datasets import load_dataset
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

"""## Load Dataset
We load the Arabic dialect dataset and convert it into a pandas DataFrame for easier processing.
"""

dataset = load_dataset("dataflare/arabic-dialect-corpus")
df = pd.DataFrame(dataset["train"])

df.head()

"""## Dataset Overview
We keep only the relevant columns needed for this task:
- `text`: the Arabic sentence
- `dialect`: the dialect label
"""

df = df[["text", "dialect"]].dropna().copy()

print("Dataset shape:", df.shape)
df.head()

df["dialect"].value_counts()

"""## Initial Dialect Distribution
This plot shows the class distribution before filtering the dataset.
"""

plt.figure(figsize=(10, 5))
sns.countplot(x="dialect", data=df, order=df["dialect"].value_counts().index)
plt.title("Dialect Distribution Before Filtering")
plt.xticks(rotation=45)
plt.show()

"""## Select Target Dialects
For this experiment, we focus on binary classification between:
- Khaleeji
- Masri
"""

selected_dialects = ["Khaleeji", "Masri"]
df = df[df["dialect"].isin(selected_dialects)].copy()

df["dialect"].value_counts()

"""## Balance the Dataset
To avoid bias toward one class, we balance the dataset by sampling the same number of examples from each dialect.
"""

min_samples = df["dialect"].value_counts().min()

df = (
    df.groupby("dialect", group_keys=False)
      .apply(lambda x: x.sample(min_samples, random_state=42))
      .reset_index(drop=True)
)

df["dialect"].value_counts()

plt.figure(figsize=(6, 4))
counts = df["dialect"].value_counts()
sns.barplot(x=counts.index, y=counts.values)
plt.title("Balanced Dialect Distribution")
plt.ylabel("Count")
plt.show()

"""## Text Cleaning
Arabic text may contain punctuation, digits, and extra spaces.  
We apply basic preprocessing to standardize the text before training.
"""

def clean_text(text):
    text = str(text)

    text = re.sub(r"[^\w\s\u0600-\u06FF]", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "و", text)
    text = re.sub("ئ", "ي", text)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"[؟،؛!.,]", "", text)
    return text

"""## Cleaned Text Example

Below is a comparison between the original text and the cleaned version after preprocessing.
"""

df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text"]].head()

"""Note:
I intentionally avoid aggressive text cleaning to preserve dialect-specific features, which are essential for accurate classification.

## Prepare Features and Labels
We use the cleaned text as input and the dialect labels as targets.
"""

X = df["clean_text"]
y = df["dialect"]

"""## Train-Test Split
i split the dataset into training and testing sets while preserving class balance using stratification.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

"""## Encode Labels
The dialect labels are converted into numeric values for model training.
"""

encoder = LabelEncoder()
y_train_enc = encoder.fit_transform(y_train)
y_test_enc = encoder.transform(y_test)

print("Classes:", list(encoder.classes_))

"""## Model 1: Logistic Regression with TF-IDF
First, we train a traditional machine learning baseline using TF-IDF features and Logistic Regression.
"""

tfidf = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=8000
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

lr = LogisticRegression(max_iter=2000)
lr.fit(X_train_tfidf, y_train_enc)

pred_lr = lr.predict(X_test_tfidf)

"""## Logistic Regression Evaluation
i evaluate the model using:
- Accuracy
- Classification report
- Confusion matrix
"""

lr_accuracy = accuracy_score(y_test_enc, pred_lr)
print("Logistic Regression Accuracy:", lr_accuracy)
print()
print(classification_report(y_test_enc, pred_lr, target_names=encoder.classes_))

cm_lr = confusion_matrix(y_test_enc, pred_lr)

plt.figure(figsize=(6, 4))
sns.heatmap(
    cm_lr,
    annot=True,
    fmt="d",
    xticklabels=encoder.classes_,
    yticklabels=encoder.classes_,
    cmap="Blues"
)
plt.title("Confusion Matrix - Logistic Regression")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""## Model 2: LSTM
Next, i train a deep learning model using tokenized and padded text sequences.
"""

tokenizer = Tokenizer(num_words=30000)
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=120)
X_test_pad = pad_sequences(X_test_seq, maxlen=120)

model = Sequential([
    Embedding(input_dim=30000, output_dim=128, input_length=120),
    LSTM(128),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

model.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

model.summary()

"""## Train the LSTM Model
i train the LSTM model and monitor validation performance.
"""

history = model.fit(
    X_train_pad,
    y_train_enc,
    epochs=5,
    batch_size=64,
    validation_split=0.1,
    verbose=1
)

loss, lstm_accuracy = model.evaluate(X_test_pad, y_test_enc, verbose=0)
print("LSTM Accuracy:", lstm_accuracy)

"""## Compare Model Performance
We compare the final test accuracy of both models.
"""

results = {
    "Logistic Regression (TF-IDF)": lr_accuracy,
    "LSTM": lstm_accuracy
}

results_df = pd.DataFrame.from_dict(results, orient="index", columns=["Accuracy"])
results_df

"""## Model Comparison

The LSTM model outperformed Logistic Regression (TF-IDF).

- Logistic Regression Accuracy: 88.2%
- LSTM Accuracy: 93.3%

The improvement shows that LSTM captures contextual patterns more effectively.
"""

plt.figure(figsize=(6, 4))
sns.barplot(x=results_df.index, y=results_df["Accuracy"])
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.ylim(0, 1)
plt.show()

"""## Test on Custom Samples
Finally, i test the trained models on manually written Arabic samples.
"""

samples = [
    "وش أخبارك اليوم؟",
    "إزيك عامل ايه؟",
    "شلونك شخبارك؟",
    "حاسب يا أسطى",
    "انت بتعمل ايه؟",
    "رحت لدوامك اليوم؟",
    "عايز آكل حاجة على الماشي",
    "قشطه يا معلم",
    "سلام عليكم",
    "يا ابني انت مسطول ولا ايه",
    "وش مشكلتك انت",
    "استح على وجهك",
    "استح على دمك",
    "عايز أشتري عربية جديدة",
    "أبغى أشتري سيارة جديدة",
    "رايح فين دلوقتي؟",
    "وين رايح الحين؟",
    "ما عليه، تصير خير",
    "الموضوع ده بسيط خالص",
    "شنو رايك في الموضوع؟"
]

clean_samples = [clean_text(text) for text in samples]

sample_tfidf = tfidf.transform(clean_samples)
sample_preds_lr = lr.predict(sample_tfidf)
sample_labels_lr = encoder.inverse_transform(sample_preds_lr)

pd.DataFrame({
    "Text": samples,
    "Predicted Dialect (LR)": sample_labels_lr
})

sample_seq = tokenizer.texts_to_sequences(clean_samples)
sample_pad = pad_sequences(sample_seq, maxlen=120)

sample_preds_lstm = (model.predict(sample_pad) > 0.5).astype("int32").flatten()
sample_labels_lstm = encoder.inverse_transform(sample_preds_lstm)

pd.DataFrame({
    "Text": samples,
    "Predicted Dialect (LR)": sample_labels_lr,
    "Predicted Dialect (LSTM)": sample_labels_lstm
})

"""The LSTM model performs better on context-dependent expressions, while Logistic Regression struggles with phrases that require understanding of dialect-specific usage.

## Conclusion

In this project, I built and evaluated two approaches for Arabic dialect classification: Logistic Regression with TF-IDF and an LSTM-based model.

The results show that the LSTM model outperformed Logistic Regression on the test set, achieving higher accuracy (93.3% vs 88.2%). This indicates that LSTM is more effective at capturing contextual and sequential patterns in Arabic text.

Through this project, I found that:
- Text preprocessing plays an important role, but should be kept minimal for dialect tasks
- Traditional models perform well on surface-level patterns
- Deep learning models can better capture context-dependent expressions

Overall, this project demonstrates how different modeling approaches impact performance in Arabic NLP tasks, and highlights the importance of choosing the right model for the problem.

## Future Work

To further improve this project, I plan to extend both the data and modeling approaches.

Future enhancements include:
- Expanding the classification task to multiple Arabic dialects
- Improving Arabic text normalization and preprocessing techniques
- Applying advanced deep learning models such as transformer-based architectures (e.g., AraBERT)
- Performing systematic hyperparameter tuning for both models
- Deploying the model as a simple web application

### Notes

This project was developed as an individual effort to explore Arabic dialect classification using both traditional machine learning and deep learning approaches.
"""